workflows:
  flutter-ios:
    name: Flutter iOS
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter packages pub get

      - name: Set up Xcode project  # ← 追加
        script: |
          cd ios
          pod repo update
          pod install

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload/
    artifacts:
      - build/ios/iphoneos/app.ipa