workflows:
  flutter-ios:
    name: Flutter iOS
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean
        script: flutter clean
        
      - name: Get dependencies
        script: flutter pub get

      - name: Build unsigned IPA
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload/

    artifacts:
      - build/ios/iphoneos/app.ipa